---
- name: Make sure Vim is installed on Archlinux
  pacman: name="{{item}}" state=latest
  with_items:
    - vim
  when: ansible_distribution == "Archlinux"

- name: Make sure Vim is installed on Ubuntu/Debian
  apt: name="{{item}}" state=latest
  with_items:
    - vim
  when: ansible_os_family == "Debian"

- name: Global vim config on Archlinux
  copy: src=vimrc-arch dest=/etc/vimrc owner=root group=root mode="u=rw,g=r,o=r"
  when: ansible_distribution == "Archlinux"

- name: Global vim config on Archlinux
  copy: src=vimrc-deb dest=/etc/vim/vimrc owner=root group=root mode="u=rw,g=r,o=r"
  when: ansible_os_family == "Debian"
