---

- name: Add official MariaDB apt key
  apt_key: id={{mariadb_repo_key_id}} keyserver={{mariadb_repo_key_url}} state=present
  when: ansible_os_family == 'Ubuntu' and ansible_distribution_version == '14.04'

- name: Add official MariaDB 10.1 repository for Ubuntu LTS 14.04
  apt_repository: repo="{{mariadb_repo}}" state=present update_cache=yes
  when: ansible_os_family == 'Ubuntu' and ansible_distribution_version == '14.04'

- name: Installing MariaDB Server package
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - "{{mariadb_server_package}}"
  notify: stop mariadb

