---
# This role contains common tasks that are perfomed on all Debian-based nodes.

- name: Update all packages to the latest version
  apt: upgrade=dist update_cache=yes

- name: Remove password prompt for sudo
  lineinfile: "dest=/etc/sudoers state=present regexp='^%sudo' line='%sudo ALL=(ALL) NOPASSWD: ALL'"

# Install and configure Vim 
- name: Make sure Vim is installed
  apt: name=vim state=latest

- name: Configure vimrc file
  copy: src=etc/vim/vimrc dest=/etc/vim/vimrc owner=root group=root mode="u=rw,g=r,o=r"

# Set Time Zone
- name: Set timezone
  timezone: name={{ timezone }}

# Colored prompt for new users
- name: Colored prompt for new users
  lineinfile: dest=/etc/skel/.bashrc state=present regexp='^#force_color_prompt=yes' line='force_color_prompt=yes'

